### ISSUE TITLE
PSAL CF standard name should be sea_water_practical_salinity

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#10]
The CF standard name for PSAL is “sea_water_practical_salinity”
Argo uses a deprecated “sea_water_salinity”

The change to “sea_water_practical_salinity” should not be performed in short term, we shall wait for the next significant format change.
On NVS Argo R03 PSAL entry, there is a link to “sea_water_practical_salinity” 
http://vocab.nerc.ac.uk/collection/R03/current/PSAL/

**Comment by matdon17** [comment]
As discussed during ADMT21, I propose that on the NVS we have mappings to both the current “sea_water_practical_salinity”
and the deprecated “sea_water_salinity” terms, until such time as the Argo Data System implements the change, and then we can drop the mapping to “sea_water_salinity”.

**Comment by vpaba** [comment]
This is a request for a netCDF format change, so wondering if the ticket should be moved elsewhere. @nvs-vocabs/avtt, @tcarval could you please advise where netCDF format update requests are kept? I remember a Google Document but can't find it anymore - it may have been for a previous ADMT only though. Is there a list ahead of this year's ADMT? Otherwise would this EuroArgo GitHub repo be appropriate? https://github.com/euroargodev/ArgoNetCDF

**Comment by tcarval** [comment]
Hello Violetta, here is the link to the ARgo NetCDF format changes document https://docs.google.com/document/d/1DSFcJa1LCuZQxPJorX_Z00GQkF1OIEdXdVWlH1NexN0/edit?usp=sharing
