### ISSUE TITLE
R08 : New entries - SOLOBGC, PROVOR III and V

### ISSUE THREAD

**Issue by vturpin** [nvs-vocabs/ArgoVocabs#69]
New addition to the CCT C-3 have been requested, see status of: https://github.com/wmo-im/CCT/issues/134

884 - "SOLO_BGC, SBE"
885 - " SOLO_BGC, RBR"
886 - "SOLO_BGC_MRV, SBE"
887 - "SOLO_BGC_MRV, RBR"

888 - "PROVOR_V - Jumbo, SBE"
889 - "PROVOR_V - Jumbo, RBR"
890 - "PROVOR_III - Jumbo, SBE"
891 - "PROVOR_III - Jumbo, RBR"

Those 8 entries should be added to R08 too.

**Comment by tcarval** [comment]
- [x] Done on NVS
- [x] Done on format checker : https://github.com/euroargodev/ArgoNetCDF/tree/v2.8.5
- [x] Active on Coriolis GDAC
- [ ] Active on US GDAC

**Comment by gmaze** [comment]
weird: "PROVOR_III" seems to have disappeared from R08 as 836 ?

**Comment by tcarval** [comment]
@gmaze, thank you Guillaume for spotting that.
These 834, 835 and 836 floats are perfectly valid, but do not appear in the NVS.
@vpaba, Violetta is there a reason for that ?
I just submitted these 3 definitions in the R08 table.
They should appear soon.

**Comment by vpaba** [comment]
Hi @tcarval,  Thanks for this - I checked R08 and there was no record of 834, 835 and 836 on our side, which is strange! It could be that they were never created, because otherwise we'd expect them to see them as deprecated at most, like mentioned above. Are these three codes already present in CCT C-3 @vturpin ? 
We've received these new submissions and they have been approved, so they should appear on the NVS tomorrow. 

One thing I noticed, the last few submissions (890, 891, 889, 881, 882, 884, 885, 886, 887, 888, 834, 835, 836) don't have an 'alternative label' / CODVAL specified (which had been the same as the Identifier for R08) - would you like me to update this so that it's consistent with the rest of the list, or is it no longer necessary?

Thank you,
Violetta

**Comment by vturpin** [comment]
Yes 834, 835 and 836 are already in the CCT C-3.
I found it here: https://github.com/wmo-im/CCT/pull/150/commits/5f234050e0b4b08838af9b7ad187ec337f4706c1#diff-80cdc2d7308f541a438e53cecec1bd0143e158d7a675ab60655150804426e78c

**Comment by tcarval** [comment]
> Hi @tcarval, Thanks for this - I checked R08 and there was no record of 834, 835 and 836 on our side, which is strange! It could be that they were never created, because otherwise we'd expect them to see them as deprecated at most, like mentioned above. Are these three codes already present in CCT C-3 @vturpin ? We've received these new submissions and they have been approved, so they should appear on the NVS tomorrow.
> 
> One thing I noticed, the last few submissions (890, 891, 889, 881, 882, 884, 885, 886, 887, 888, 834, 835, 836) don't have an 'alternative label' / CODVAL specified (which had been the same as the Identifier for R08) - would you like me to update this so that it's consistent with the rest of the list, or is it no longer necessary?
> 
> Thank you, Violetta

Yes please add 'alternative label' / CODVAL to be consistent
