### ISSUE TITLE
molar_doxy P06:MMPL unit is not correct

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#83]
Here is the molar_doxy entry in NVS:
https://vocab.nerc.ac.uk/collection/R03/current/MOLAR_DOXY/

The unit is "micromole/litre", the P06:MMPL is "Millimoles per litre".
@vpaba It should be changed to P06:UPOX

The P01 parameter is also probably not correct, refering to  P06:MMPL instead of P06:UPOX
https://vocab.nerc.ac.uk/collection/P01/current/DOXYMMOP/

@catsch The legacy excel spreadsheet should also be corrected.

**Comment by gwemon** [comment]
Hi @tcarval, Vi or Dani will be in touch when the correction is made. Completely fine to match the unit for R03 to what you have of course. For the P01, we would not normally change the unit that is displayed unless it is wrong (i.e. wrong vector dimension). This is because the unit associated with a P01 is not mandatory but only indicative (i.e. a suggestion). Ideally we should couple a P01 to a P24 vector dimension so that the user is not led to believe that the unit displayed is the one that should be used. However our own internal BODC systems (legacy!) depend on a 1-2-1 association between P01 and P06. Until this is addressed we will have to maintain that 1-2-1 mapping between P01 and P06. However we have checked our databases and it looks like this parameter code was never used internally. It is also unlikely to have been used externally with that unit. So for this reason we will change the unit to being micromole per litre to be consistent with expected data output whenever DO is expressed in molar concentration per liter.  What I suspect happened, is that the unit of mmol/l was a direct "translation" from the CF standard canonical unit of mol per cubic meter (i.e. SI unit for amount of substance over SI unit for volume). The mapping was created in 2014 and, at the time, BODC tended to express volume on a per litre basis rather than a per cubic meter basis. Sorry for the long message but I thought it was important to have this explained in detail for future reference. Many thanks. Gwen.

**Comment by danibodc** [comment]
Hi @tcarval, I have now updated the mappings so that both R03:MOLAR_DOXY and P01:DOXYMMOP are mapped to P06:UPOX. You should see the changes on the NVS tomorrow morning after the overnight refresh. Many thanks!
